### ISSUE TITLE
Cardano BIP39 wallet key derivation method appears to differ from Daedalus and Yoroi

### ISSUE THREAD

**Issue by dougnukem** [vacuumlabs/ledger-app-cardano-shelley#82]
I'm trying to understand how to use a BIP39 recovery seed that I used in Daedalus / Yoroi wallets with Ledger Cardano.

It appears that whatever BIP39 derivation those wallets use is not the same as being used by Ledger or this ledger-app-cardano?

Is it possible to import a Daedalus BIP39 recovery into Ledger or is the only feasible path to transfer the ADA into the new Ledger derived wallet after import?

What BIP39/BIP44 key derivation paths does this implement and does anyone know how that differs from Yoroi or Daedalus?
- https://github.com/vacuumlabs/ledger-app-cardano-shelley/blob/develop/src/keyDerivation.c

It appears the Cardano team has documented various Cardana wallet key generation methods:
- https://github.com/cardano-foundation/CIPs/blob/master/CIP-0003/CIP-0003.md

The recommended method is what Daedulus and Yoroi wallets use:
- https://github.com/cardano-foundation/CIPs/blob/master/CIP-0003/Icarus.md

I know it would impact backwards compatibility but is there any path towards having the Ledger cardano app support this wallet key generation method or some way to derive both wallet keys?

**Comment by refi93** [comment]
Hi @dougnukem, unfortunately, Ledger derives the seed from the mnemonic at firmware level (see https://github.com/vacuumlabs/ledger-app-cardano-shelley/blob/25abe583572ab0a2e458fbf592e8e68cb3ba3912/src/keyDerivation.c#L53 - this is a firmware-level command) and it's different from what Cardano wallet like Daedalus or Yoroi as the Icarus scheme. AFAIK ledger apps don't have direct access to the device mnemonic due to security. Changing the derivation scheme/adding new ones in Ledger would therefore require modifying the Ledger firmware itself which is not open-source.

Moreover, adding support for multiple derivation schemes would end up being potentially a big source of confusion for Ledger users, making an addition for such feature to the firmware rather hard to justify.

Even if we overcome these obstacles, Ledger doesn't offer recovery from 15 word mnemonics (only 12, 18, 24 - https://www.ledger.com/blog/how-to-protect-your-seed-phrase), which is the default mnemonic length of Daedalus/Yoroi wallets so even if Ledger used the same seed derivation, it wouldn't allow you to use your Daedalus/Yoroi mnemonic, at least the 15-words one, so 24 word ones would be the only viable option (provided Ledger somehow supported the same derivation)

As a general note - it doesn't seem advisable to import software wallet mnemonics to hw wallets as that violates the basic security assumption behind hw wallets that their mnemonic wasn't ever exposed to any electronic device and such mnemonics are therefore inherently less secure than the ones generated directly on the Ledger device

Given the issues described above we unfortunately don't see any path to make Daedalus/Yoroi derivation work on Ledger in the foreseeable future.
